route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'stagent9@gmail.com'
        auth_identity: 'stagent9@gmail.com'
        auth_password: '${ALERTMANAGER_APP_PWD}'
        from: 'stagent9@gmail.com'
        to: 'maxxromagnoli@gmail.com, zonel@tcd.ie, oyelakua@tcd.ie, binliw@tcd.ie, ariyoc@tcd.ie, mccooeyc@tcd.ie, kryukovd@tcd.ie, ohorodnk@tcd.ie, adilr@tcd.ie'
        #to: 'maxxromagnoli@gmail.com, zonel@tcd.ie'
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
