route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - smarthost: '<host-email-here>:587'
        auth_username: '<host-email-here>'
        auth_identity: '<host-email-here>'
        auth_password: '${ALERTMANAGER_APP_PWD}'
        from: '<sender-email-here>'
        to: '<receiver-email-here1>, <receiver-email-here2>'
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
