{
 "title": "machine-more-cpu",
 "description": "Displays detailed metrics of a single node in the server.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-weight: 900; font-size: 60px;\">CPU</p>\n\n"
   }
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "description": "The average percentage of non-idle time for all CPU cores in the last 15s",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[15s])) * 100\n\n",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Utilization By Core",
   "type": "timeseries",
   "description": "Usage per core",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"0\"}[5m]) * 100) ",
     "legendFormat": "CPU 0"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"1\"}[5m]) * 100) ",
     "legendFormat": "CPU 1"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"2\"}[5m]) * 100) ",
     "legendFormat": "CPU 2"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"3\"}[5m]) * 100) ",
     "legendFormat": "CPU 3"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"4\"}[5m]) * 100) ",
     "legendFormat": "CPU 4"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"5\"}[5m]) * 100) ",
     "legendFormat": "CPU 5"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"6\"}[5m]) * 100) ",
     "legendFormat": "CPU 6"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"7\"}[5m]) * 100) ",
     "legendFormat": "CPU 7"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\n",
     "legendFormat": "Idle time"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[5m]))",
     "legendFormat": "User space "
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[5m]))",
     "legendFormat": "System space"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))",
     "legendFormat": "I/O wait"
    },
    {
     "expr": "1 - (\n  sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m])) +\n  sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m])) +\n  sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) +\n  sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n) / sum(rate(node_cpu_seconds_total[5m]))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Idle v. Busy",
   "type": "piechart",
   "description": "The proportion of idle time and non-idle time",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\n\n",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "title": "Busy",
   "type": "bargauge",
   "description": "Proportion of each item in non-idle time\n",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100",
     "legendFormat": "User space "
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100\n\n",
     "legendFormat": "System space "
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100",
     "legendFormat": "I/O Wait"
    },
    {
     "expr": "100 - (\n  (sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100 +\n  (sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100 +\n  (sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100\n)",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "CPU Temperature ",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User space",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System space",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Interrupts",
   "type": "timeseries",
   "description": "The number of times the CPU handles hardware or software interrupts",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 27 },
   "targets": [
    { "expr": "rate(node_intr_total[1m])\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "description": "GHz\nThresholds(>80, <20)\nStatus",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{ job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"your_job_name\"}[5m])) * 100)) > 80",
     "legendFormat": "{{Upper}}"
    },
    {
     "expr": "(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"your_job_name\"}[5m])) * 100)) < 20",
     "legendFormat": "{{Lower:}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "description": "Speed&Maximum Speed",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_cpu_frequency_hertz)", "legendFormat": "{{Current Speed}}" },
    {
     "expr": "node_cpu_frequency_max_hertz{instance=\"your_instance\"}",
     "legendFormat": "{{Maximum Speed}}"
    }
   ]
  },
  {
   "title": "Context Switch",
   "type": "timeseries",
   "description": "The increment of the number of context switches in one minute and converts it to an average per second",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 37 },
   "targets": [
    { "expr": "node_context_switches_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average CPU load",
   "type": "timeseries",
   "description": "Average load metrics for the past 1, 5, and 15 minutes are provided",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 38 },
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "1 min" },
    { "expr": "node_load5{}", "legendFormat": "5 min" },
    { "expr": "node_load15{}", "legendFormat": "15 min" }
   ]
  },
  {
   "title": "System load(5m avg)",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"$node\",job=\"$job\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}