{
 "title": "machine",
 "description": "Displays detailed metrics of a single node in the server.",
 "time": { "from": "2024-03-27T14:17:52.710Z", "to": "2024-03-27T14:47:52.710Z" },
 "templating": {
  "list": [
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"python_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 \r\n  style=\"overflow: hidden; color: #8c4fff; font-size: 35px; font-weight: bold\"\r\n>\r\n\r\nDashboard\r\n\r\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "options": {
    "content": "<h1 style=\"padding-top: 10px; overflow: hidden;\">CPU</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 2 },
   "options": {
    "content": "<h1 style=\"padding-top: 10px; overflow: hidden;\">Memory</h1>"
   }
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "description": "The average percentage of non-idle time for all CPU cores in the last 15s",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_cpu_utilization_overall_percentage{instance=\"$exporter\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "The average percentage of non-idle time for all CPU cores in the last 15s",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "stagent_cpu_utilization_overall_percentage{instance=\"$exporter\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "description": "The amount of RAM(random access memory) in use",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_ram_utilization_percentage{instance=\"$exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "100 - stagent_ram_utilization_percentage{instance=\"$exporter\"}",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Usage Overtime",
   "type": "timeseries",
   "description": "RAM usage over a period of time",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "stagent_ram_utilization_percentage{instance=\"$exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "100 - stagent_ram_utilization_percentage{instance=\"$exporter\"}",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Freq",
   "type": "gauge",
   "description": "Provides real-time data of the CPU's current operating frequency",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_cpu_frequency_current_mhz{instance=\"$exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "stagent_cpu_frequency_current_mhz{instance=\"$exporter\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 10 },
   "options": {
    "content": "<h1 style=\"padding-top: 15px; overflow: hidden;\">Network</h1>"
   }
  },
  {
   "title": "Traffic In",
   "type": "gauge",
   "description": "The amount of data entering a specified network or system",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_traffic_in_mbs{instance=\"$exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "The amount of data being received over the network interface named \"eth0\" ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "stagent_traffic_in_mbs{instance=\"$exporter\"}",
     "legendFormat": "eth0"
    }
   ]
  },
  {
   "title": "Busy",
   "type": "bargauge",
   "description": "Proportion of each item in non-idle time\n",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100\n\n",
     "legendFormat": "System"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))/ \nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100",
     "legendFormat": "I/O Wait"
    },
    {
     "expr": "100 - (\n  (sum(rate(node_cpu_seconds_total{mode=\"user\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100 +\n  (sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100 +\n  (sum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) / sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) * 100\n)",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "gauge",
   "description": "The amount of data that leaves a specified network or system",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_traffic_out_mbs{instance=\"$exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "The amount of data being sent out through the \"eth0\" network interface",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "stagent_traffic_out_mbs{instance=\"$exporter\"}",
     "legendFormat": "eth0"
    }
   ]
  },
  {
   "title": "Logical core",
   "type": "timeseries",
   "description": "Average CPU usage per logical core in the non-idle state",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 27 },
   "options": {
    "content": "<h1 style=\"padding-top: 15px; overflow: hidden;\">Disk</h1>"
   }
  },
  {
   "title": "Used v. Free",
   "type": "piechart",
   "description": "Disk space usage",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stagent_disk_total_space_bytes{instance=\"$exporter\"} - stagent_disk_free_space_bytes{instance=\"$exporter\"}",
     "legendFormat": "Used"
    },
    { "expr": "stagent_disk_free_space_bytes", "legendFormat": "Unused" }
   ]
  },
  {
   "title": "Capacity Overtime",
   "type": "timeseries",
   "description": "Disk capacity usage over a period of time",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "stagent_disk_total_space_bytes{instance=\"$exporter\"} - stagent_disk_free_space_bytes{instance=\"$exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "stagent_disk_free_space_bytes{instance=\"$exporter\"}",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Read & Write Rate",
   "type": "timeseries",
   "description": "Measures the speed of data read and write operations completed in 5min",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(stagent_disk_writes_bytes{instance=\"$exporter\"}[5m])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(stagent_disk_reads_bytes{instance=\"$exporter\"}[5m])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "How many read and write operations can be performed per second on the disk",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(stagent_disk_writes_ops{instance=\"$exporter\"}[5m])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(stagent_disk_reads_ops{instance=\"$exporter\"}[5m])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}