{
 "title": "try",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Normal processes executing in user mode",
   "type": "stat",
   "description": "Used to monitor CPU time usage",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization rate",
   "type": "gauge",
   "description": "current rate",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System updating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "description": "GHz\nThresholds(>80, <20)\nStatus",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{ job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"your_job_name\"}[5m])) * 100)) > 80",
     "legendFormat": "__auto"
    },
    {
     "expr": "(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"your_job_name\"}[5m])) * 100)) < 20",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz)\n",
     "legendFormat": "{{Current Speed}}"
    },
    {
     "expr": "node_cpu_frequency_max_hertz{instance=\"your_instance\"}",
     "legendFormat": "{{Maximum Speed}}"
    }
   ]
  },
  {
   "title": "Average CPU load",
   "type": "stat",
   "description": "Average load metrics for the past 1, 5, and 15 minutes are provided",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running\n", "legendFormat": "__auto" },
    {
     "expr": "node_load1{instance=\"your_instance\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"your_instance\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=\"your_instance\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilisation ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}