apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: false
  - name: Prometheus-Docker
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Prometheus-Azure
    type: prometheus
    access: proxy
    url: http://20.93.119.35:9090
    isDefault: false
    editable: false